
-- Add real estate products to the existing Imóveis category and subcategories
DO $$
DECLARE
    imoveis_category_id uuid;
    residencial_subcat_id uuid;
    comercial_subcat_id uuid;
    rural_subcat_id uuid;
BEGIN
    -- Get the existing "Imóveis" category ID
    SELECT id INTO imoveis_category_id FROM categories WHERE name = 'Imóveis';
    
    -- Get existing subcategory IDs
    SELECT id INTO residencial_subcat_id FROM subcategories WHERE name = 'Residencial' AND category_id = imoveis_category_id;
    SELECT id INTO comercial_subcat_id FROM subcategories WHERE name = 'Comercial' AND category_id = imoveis_category_id;
    SELECT id INTO rural_subcat_id FROM subcategories WHERE name = 'Rural' AND category_id = imoveis_category_id;
    
    -- Insert residential properties
    INSERT INTO products (name, description, price, category_id, subcategory_id, published, featured, stock_quantity) VALUES
    ('Sobrado de Alto Padrão no Alphaville em Goiânia', 'Sobrado de alto padrão com 4 suítes, incluindo uma master com closet e hidromassagem. Lazer completo com piscina aquecida, sauna molhada e espaço gourmet montado. Acabamento moderno, situado em frente à mata, na melhor localização do condomínio. Área de terreno de 650m² e 368m² de construção.', 4150000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento com 3 Suítes no Jardim Goiás', 'Apartamento de 149m² com 3 suítes, sendo uma master com closet e hidromassagem. Sala com 3 ambientes fechada em cortina de vidro, projeto de iluminação e revestimentos exclusivos. Prédio moderno com lazer completo, incluindo academia, piscina aquecida e quadra poliesportiva. Excelente localização.', 1150000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado de Alto Padrão no Condomínio Anaville em Anápolis', 'Sobrado com 5 suítes, sendo uma master com closet e hidromassagem. Lazer completo com piscina aquecida e espaço gourmet. Acabamento super premium, imóvel diferenciado.', 2800000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Mega Casa de Altíssimo Padrão no Aldeia do Vale, Goiânia', 'Residência moderna com 5 quartos, incluindo 4 suítes e escritório. Acabamentos de alto padrão com mármores, granitos e quartizitos. Lazer com piscina de borda infinita aquecida, ofurô, automação completa, elevador e paisagismo sofisticado. Terreno de 2.471m² e 670m² de construção. Projetos e móveis assinados por renomados profissionais.', 11500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa de Alto Padrão no Setor Jaó, Goiânia', 'Sobrado com 4 suítes, sendo uma no térreo, piscina aquecida com cascata e hidromassagem, cozinha e área gourmet integradas com churrasqueira a carvão. Lote de esquina com 446m² e 302,65m² construídos. Acabamento premium, esquadrias com blackout automatizado e projeto arquitetônico moderno. Garagem sem colunas para maior espaço.', 2080000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Mega Sobrado de Alto Padrão no Jardins Itália, Goiânia', 'Sobrado de 366m² em lote de 525m² com 4 suítes grandes, home cinema, venezianas automatizadas e fachada imponente com porta pivotante de 6 metros. Lazer com piscina aquecida, paisagismo completo e sistema de irrigação. Suíte master com closet e varanda, com pé direito de 3 metros na sala. Acabamento em porcelanato 120x120, bancadas em quartzito e mármore, além de rodapé embutido.', 5450000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Mega Apartamento de Alto Padrão no Setor Marista – Opus Penthouses', 'Apartamento novo com 270m² e 4 suítes, incluindo uma master, 3 vagas de garagem e piscina aquecida particular. Prédio moderno com lazer completo e alto padrão de acabamento.', 3150000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa Térrea de Altíssimo Padrão no Condomínio Jardins Itália, Goiânia', 'Casa térrea de 301m² em terreno de 525m² com 4 suítes, incluindo uma master com closet e hidromassagem dupla. Ampla sala com 4 ambientes, escritório, piscina aquecida, ofurô e espaço gourmet completo. Acabamento premium, revestimentos exclusivos e projeto de iluminação arrojado. Imóvel climatizado e muito exclusivo.', 5990000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Mega Casa no Condomínio Portal do Sol Green, Goiânia', 'Sobrado com 4 suítes, sendo uma master, piscina aquecida e spa. Ampla sala com pé direito duplo, acabamentos e acessórios exclusivos, projeto de iluminação elaborado por arquiteto renomado. Terreno de 654m² e 501m² de construção. Localização premium no condomínio.', 4500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Mega Apartamento de Alto Padrão no Lago das Rosas, Goiânia', 'Apartamento de 360m² com 3 suítes, uma master com closet, escritório, ampla sala com 4 ambientes e varanda gourmet com churrasqueira. Vista para o lago e 5 vagas de garagem. Prédio novo com alto padrão de acabamento e lazer completo.', 2950000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Surpreendente Apartamento no Vaca Brava, Goiânia', 'Apartamento de luxo com 397m² no Epic City Home. Pé direito alto, vista para o lago, sala com 5 ambientes, espaço gourmet com churrasqueira, 4 suítes amplas com suíte master que possui closet e hidromassagem moderna. Acabamentos exclusivos em mármores importados e metais sofisticados. Projeto de iluminação e mobília assinada.', 4990000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de Alto Padrão no Setor Marista, Goiânia', 'Apartamento mobiliado e decorado com 312m², 3 suítes amplas com sala íntima que pode ser transformada em 4ª suíte. Imóvel totalmente automatizado, 3 vagas de garagem e vista definitiva e panorâmica.', 3000000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Conforto e Modernidade no Edifício Sinfonia Eco Design, Setor Marista', 'Apartamento exclusivo com projeto de interiores assinado. São 3 suítes, hall e elevador privativo, sala integrada à cozinha, varanda gourmet, office, home, área de serviço ampliada e DCE. Suíte master com closet, banheiro com jacuzzi e cubas duplas. Automatização completa, sistema de som surround, móveis laqueados, marcenaria planejada, piso cimento queimado polido e projeto luminotécnico. Localizado em andar alto, posição nascente.', 3990000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado à Venda no Jardins Porto com 3 Suítes', 'Sobrado de 207m² em terreno de 359m² com 4 quartos (3 suítes), 5 banheiros e 4 vagas de garagem. Sala com dois ambientes, cozinha americana, área gourmet com churrasqueira e piscina aquecida com hidromassagem. Energia fotovoltaica, porcelanato e condomínio com lazer completo e segurança 24 horas.', 1900000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado com 3 Suítes, Office, Home Theater e Piscina no Jardins Atenas', 'Sobrado no condomínio Jardins Atenas com 3 suítes planejadas, escritório, home theater, área de serviço, cozinha equipada com armários embutidos e eletrodomésticos. Área externa com varanda gourmet, churrasqueira, piscina, pátio e jardim, projetado para proporcionar luxo, conforto e qualidade de vida.', 3495000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Atmos City – 4 Suítes com Piscina no Setor Marista', 'Apartamento de 247m² no Atmos City Design, com 4 suítes, 6 banheiros, 3 vagas de garagem e escaninho. Varanda gourmet com piscina integrada à sala. Cozinha moderna, fechadura digital, espera para ar-condicionado e lazer completo no prédio. Localizado em bairro estratégico próximo a escolas e comércio. Entrega prevista para outubro de 2025.', 2990000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa Térrea e Mobiliada com 3 Suítes no Aldeia do Vale', 'Sofisticação, conforto e integração com a natureza definem esta casa com 3 suítes no condomínio Aldeia do Vale. Projeto arrojado e acabamento de alto padrão, com hall de entrada imponente, salas com móveis icônicos assinados por renomados designers brasileiros, lazer externo com móveis de designers de destaque e paisagismo exuberante. Piscina com deck de madeira, espaço gourmet com churrasqueira, bar e pergolado. Privacidade, segurança e localização privilegiada perto de comércio, escolas e alta gastronomia.', 7950000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Exclusividade no Setor Marista – Apartamento de Luxo com 270m²', 'Apartamento exclusivo no Setor Marista, Goiânia, com entrega prevista para maio de 2025. 4 suítes amplas, piscinas privativas personalizáveis, ventilação cruzada e iluminação natural. Projeto arquitetônico e paisagismo de prestígio com design de interiores sofisticado. Lazer completo com academia, sauna, spa, brinquedoteca, salão de festas e playground. Sustentabilidade com materiais duráveis, controle de acesso 24h e elevadores privativos. Localização privilegiada próximo a restaurantes, escolas e comércio.', 3490000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado à Venda com 417 m² no Residencial Granville', 'Casa moderna de 417 m² com 5 amplas suítes, arquitetura contemporânea e acabamentos de alta qualidade. Espaços planejados com sala de estar espaçosa, cozinha gourmet, área de lazer com piscina e segurança do condomínio Granville. Terreno de 465 m², 3 vagas de garagem e imóvel pronto para morar. Oportunidade de investir em conforto e elegância em local prestigiado.', 3300000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa de Condomínio Estilo Toscana com 4 Suítes no Aldeia do Vale, Goiânia', 'Residência inspirada na Toscana com 4 quartos (4 suítes), 7 banheiros, em terreno de 5.558 m² com ampla área verde e lazer completo. Espaços amplos e privativos, três vagas de garagem, segurança e tranquilidade em condomínio premium. Ideal para famílias que valorizam conforto, exclusividade e qualidade de vida.', 6200000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 262 m² em Frente à Praça T-23, Setor Bueno', 'Apartamento com 4 suítes, cozinha americana integrada, varanda gourmet, espaço gourmet e ampla área social no Setor Bueno. Condomínio com piscina, academia, área de churrasqueira, salão de festas e coworking. Localização excelente próxima a shoppings, escolas, restaurantes e áreas de lazer na capital.', 3450000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Kalea Jardins de 368 m² – Esquina da Consolação com Lorena, São Paulo', 'Apartamento à venda em construção, com 4 suítes, 4 vagas de garagem, um por andar, em localização exclusiva de São Paulo. Condomínio completo com academia, piscina, campo de futebol, salão de festas, brinquedoteca e mais. Gás individual, terraço e elevador privativo, oferecendo privacidade e conforto. Ideal para quem busca sofisticação e amplitude.', 17991480.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento 166 m² com 3 Suítes no Setor Marista', 'Apartamento de 166,92 m² no Setor Marista, Goiânia, com 3 suítes (1 master com closet), 5 banheiros, 3 vagas de garagem, varanda gourmet e amplas janelas. Localização privilegiada entre Avenida 136 e Alameda Ricardo Paranhos. Condomínio com academia, piscinas, brinquedoteca e segurança 24h. Perfeito para quem busca conforto e praticidade.', 1750000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado no Condomínio Jardins Paris com 450 m² e 4 Suítes', 'Sobrado moderno no Jardins Paris com 450 m², 4 suítes plenas com closet, sala 3 ambientes, office e lavabo. Cozinha espaçosa com balcão em granito, área de serviço independente, DCE, armários planejados, aquecimento solar e poço artesiano. Área gourmet com varanda, churrasqueira à carvão, piscina e jardim com paisagismo.', 4000000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Penthouse Opus Verti com 516 m² e 3 Suítes no Setor Marista', 'Penthouse de alto padrão com 516 m², 3 suítes, 2 salas, 5 banheiros e 5 vagas de garagem. Acervo de móveis assinados por Oscar Niemeyer, Sérgio Rodrigues e Jader Almeida. Área externa com piscina, sauna privativa, churrasqueira, escritório e ar-condicionado. Condomínio com academia, piscina aquecida, playground e portaria 24h.', 12500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Reformado de 228 m² com 3 Suítes no Park House Flamboyant', 'Apartamento semi-mobiliado em Jardim Goiás com 228 m², 3 amplas suítes (reversível para 4), varanda gourmet com pé direito duplo e vista definitiva para o Parque Flamboyant. Projeto assinado pela Woo Arquitetura, cozinha equipada e suíte master com 2 closets. Condomínio oferece piscinas climatizadas, academia, espaços gourmet e segurança.', 2790000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Mobiliado com 3 Suítes e Home no Setor Oeste', 'Apartamento de 360 m² no City Vogue Praça do Sol, com design do arquiteto Leo Romano. Conta com 4 quartos (3 suítes), 5 vagas de garagem e salas amplas. Localizado próximo à Praça do Sol, com acesso fácil a lazer e serviços. Acabamentos sofisticados e ambiente acolhedor, ideal para morar com conforto e estilo.', 4790000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado Rústico com Pomar no Condomínio Aldeia do Vale', 'Casa semi-mobiliada com 600 m² privativos em terreno de 2.820 m². Conta com 5 suítes, 6 banheiros, ampla área social com varanda, aquecimento solar, ar-condicionado, adega e cozinha integrada equipada. Jardim com pomar e pátio, escritório, hidromassagem e espaço externo para relaxamento em condomínio exclusivo.', 4350000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado com Automação e Lazer Completo no Jardim Paris', 'Sobrado moderno no Jardim Paris com energia fotovoltaica, automação de luzes, som e persianas, previsão para elevador, piscina aquecida, lago com cascata, pomar, sauna, churrasqueira à carvão, forno para pizza e spa para 7 pessoas. Com revestimentos nobres e mobiliário de marcas renomadas.', 9500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura de 4 suítes à venda no Edifício Lumina Marista, Setor Marista, Goiânia', 'Janelas que encantam pela vista panorâmica, estilo industrial único e prédio com lazer completo incluindo piscina, sauna e academia.', 5000000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura de luxo semi mobiliada com 222 m² no 24º andar do Residencial Aria das Artes, Setor Oeste, Goiânia', 'Vista de 180 graus contemplando Praça Tamandaré, jacuzzi, pergolado com churrasqueira a carvão, varanda gourmet equipada e automação inteligente. Três suítes com acabamento sofisticado e segunda cozinha funcional com bancadas em Dekton.', 2650000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento mobiliado com 4 suítes e 244 m² à venda no Reserva Parque Areião, Goiânia', 'Localização privilegiada na orla do Parque Areião, automação completa, design sofisticado, ofurô na varanda e condomínio com lazer completo. Próximo a comércios e restaurantes renomados.', 4500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Lote fundo de mata no Residencial Alphaville Flamboyant, Goiânia', 'Terreno com privacidade total em área nobre do Alphaville Flamboyant.', 4300000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento mobiliado de 528 m² com 4 suítes e 6 banheiros', 'Imóvel de alto padrão, completamente mobiliado, com ampla área de convivência, cozinha equipada e condomínio com benefícios exclusivos em Goiânia.', 8467080.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa com 4 suítes em 346 m² no Residencial Portal do Sol Garden, Goiânia', 'Projeto que alia modernidade e aconchego, piscina aquecida com jacuzzi, espaço gourmet com churrasqueira e paisagismo sofisticado. Condomínio seguro e tranquilo cercado pela natureza.', 3990000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 2 a 3 quartos com varanda gourmet no Square, Balneário Perequê, Porto Belo, SC', 'Unidades de 80 a 97 m² com até 2 suítes, varanda com churrasqueira, living integrado, vaga dupla e lazer completo com piscina, academia e salão de festas próximo à praia.', 1717000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 120 m² com 3 suítes no Romanée, Balneário Perequê, Porto Belo, SC', 'Ambiente sofisticado e funcional com varanda fechada, vista panorâmica, tecnologia inteligente, fechadura digital e lazer completo, incluindo piscina, academia e espaço pet-friendly.', 3839900.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa de praia com 4 suítes e 224 m² na Rota Ecológica dos Milagres, São Miguel dos Milagres', 'Design assinado, infraestrutura completa com lazer e serviços pet-friendly em condomínio de alto padrão à beira mar.', 4420210.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 360 m² com 4 suítes no Residencial Sky Garden Flamboyant, Jardim Goiás, Goiânia', 'Localização privilegiada com academia moderna, piscinas aquecidas, portaria 24h, segurança reforçada, vista panorâmica e ampla área de lazer.', 3346098.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento com 4 suítes e área de lazer privativa no City House, Setor Marista, Goiânia', '229 m² com 5 banheiros, 3 vagas, espaços integrados, pé direito alto, iluminação natural e localização nobre próxima ao Parque Areião.', 2987993.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento mobiliado com 4 suítes e 259 m² no Setor Marista, Goiânia', 'Imóvel de altíssimo padrão decorado por arquiteto renomado, com 7 vagas de garagem e mobiliário assinado.', 3000000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de luxo com 4 suítes e 224 m² no Setor Marista, Goiânia', 'Suíte master com closet e hidromassagem, mobiliado com armários Florense, andar alto, vista panorâmica e projeto de iluminação arrojado.', 2350000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento com 3 quartos no PROMENADE - TORRE GALERIA, Goiânia', 'Condomínio com infraestrutura completa: academia, acessibilidade, aquecimento solar, área verde, churrasqueira, elevadores, portaria 24h, segurança, piscina, sauna, salão de jogos e muito mais.', 2400000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 394 m² com 3 suítes na Orla do Vaca Brava - Epic City Home, Goiânia', 'Projeto de Arthur Casas e Claudia Zuppani, andar alto com vista panorâmica, varanda gourmet, suíte master com closet, infraestrutura para SPA e sauna, segurança avançada e lazer completo no condomínio.', 6850000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento mobiliado com 3 suítes e 359 m² na Praça T-23, Setor Bueno, Goiânia', 'Unidade por andar, decoração assinada, persianas automatizadas, vista para a praça, lazer completo e segurança 24h.', 4500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento mobiliado com 4 suítes e 244 m² no Opus Acqua, Setor Marista, Goiânia', 'Decorado por Leo Romano, andar alto, varanda gourmet com vista panorâmica, cozinha gourmet equipada, aquecimento a gás, ar condicionado, churrasqueira, banheira de hidromassagem e fechadura digital.', 3974000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento reformado, mobiliado e com 4 suítes e 386 m² no Setor Oeste, Goiânia', 'Com projeto elétrico e hidráulico novo, 17 câmeras, 13 aparelhos de ar-condicionado, armários planejados, quatro ambientes sociais, varanda gourmet, ampla suíte master, infraestrutura completa e condomínio com gerador.', 3900000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 3 suítes mobiliado com 226 m² no Ed. Gran Excellence, Setor Bueno, Goiânia', 'Varanda gourmet de quase 30 m², móveis assinados, projeto luminotécnico, home office, ar condicionado em todas as áreas, lazer completo e segurança 24 horas. Aceita permuta.', 2900000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento semi-mobiliado com 4 suítes e 228 m² no Park House Flamboyant, Jardim Goiás, Goiânia', 'Varanda gourmet com pé direito duplo e vista para o Parque Flamboyant, suíte master com dois closets, cozinha equipada, arquitetura contemporânea assinada pela Woo Arquitetura e condomínio com lazer completo.', 2790000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento com 4 suítes e 373 m² no Residencial The Place, Parque Vaca Brava, Goiânia', 'Vista para o parque, 7 vagas de garagem, hidromassagem, closet, varanda, ampla infraestrutura de lazer e segurança em condomínio exclusivo.', 4500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 181 m² no Opus Urbano', 'Experimente o privilégio de viver no Setor Marista, um dos bairros mais prestigiados de Goiânia, neste sofisticado apartamento de 181 m² no Opus Urbano. Com três suítes amplas, sala ampla de três ambientes climatizada, área gourmet com churrasqueira a carvão integrada à cozinha rica em armários planejados, posição nascente e localização privilegiada perto do Parque Areião e diversas facilidades.', 2200000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento mobiliado e decorado em frente à Praça T-23', 'Apartamento de 359 m² na Praça da T-23, Setor Bueno, com 3 suítes plenas, escritório privativo, um apartamento por andar, decoração assinada por Via Condotti e BonTempo e arquitetura do escritório Lille D Architecture. Possui persianas automatizadas Hunter Douglas, vista para a praça, lazer completo e segurança 24 horas.', 4500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Flat Mobiliado no Setor Bueno', 'Flat semimobiliado no Setor Bueno com quarto, banheiro social, lavabo, vaga de garagem, sacada com vista panorâmica, cozinha e área de serviço com armários planejados, ar condicionado e internet. Excelente localização próxima a serviços, comércio e lazer. Imóvel financiável.', 540000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Penthouse com 372 m², 3 suítes, 6 banheiros e 4 vagas de garagem, na Alameda das Rosas', 'Penthouse de alto padrão no Setor Oeste com 372 m², 3 suítes (sendo a suíte principal com dois banheiros exclusivos), 6 banheiros, 4 vagas de garagem, piso de madeira, varanda com churrasqueira, piscina e localizado no edifício Poème com academia, piscinas e segurança 24h. Projeto arquitetônico do escritório Lins Galvão e paisagismo por Fernanda Simão.', 3500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sofisticado Apartamento com 3 Suítes à Venda no Setor Marista', 'Apartamento de 226 m² no Setor Marista, com 3 suítes amplas, office, escaninho, 3 vagas de garagem, sala integrada à cozinha, varanda com piscina privativa. Localização nobre, próximo a serviços e gastronomia, com exclusividade e conforto.', 2580000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento à Venda no Areião Park, com 3 Suítes no Setor Marista', 'Apartamento de 230 m² no Setor Marista com 3 suítes, iluminação e refrigeração concluídas, armários Terra, decoração moderna com detalhes em madeira e tom de verde nas paredes. Próximo ao Parque Areião, o condomínio oferece piscina, sauna úmida, espaço fitness, elevador privativo com acesso biométrico, mirante e bicicletário.', 2200000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento à Venda Mobiliado, Residencial Monte Logan, com 4 Suítes no Setor Bueno', 'Apartamento de 207 m² mobiliado e decorado no Setor Bueno, com 4 suítes, 5 banheiros, 3 vagas de garagem individuais, escaninho, acabamento de alto padrão e localização privilegiada perto de escolas, hospitais e comércio.', 2350000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('SQNW 104 | Apartamento com 4 Suítes com Vista para o Parque Burle Max, à venda - Noroeste - Brasília/DF', 'Apartamento de 162,65 m² com 4 suítes, acabamento de alto padrão pela construtora EMPLAVI, garantindo estilo contemporâneo e durabilidade, além de 3 vagas de garagem para segurança e conveniência.', 2690000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Deck 23', 'Apartamento de alto padrão no Setor Marista com 3 suítes, 245,69 m², acabamentos impecáveis, planta inteligente, próximo a restaurantes, escolas e parques, oferecendo segurança e qualidade de vida em localização nobre.', 3229000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Epic City Home', 'Apartamento personalizável na orla do Parque Vaca Brava, com suíte master de 55,22 m² com closet e banheiro duplo, 3 suítes com persianas integradas, sala e varanda gourmet, porcelanato 120x120 cm, pé direito livre de 2,80m, rede frigorígena para ar condicionado, 5 vagas de garagem e kit mudança incluindo armários, iluminação e ar-condicionado.', 5800000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura de Alto Padrão no Residencial Europark', 'Cobertura de 330 m² no Europark com 4 suítes, office, hidromassagem, sauna particular, adega climatizada, armários planejados, iluminação de alto padrão, climatização completa, espaço gourmet com churrasqueira a carvão, 5 vagas de garagem e escaninho. Localização privilegiada ao lado de Alphaville e Shopping Flamboyant.', 3450000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Exclusivo com 3 Suítes no Sinfonia Eco Design - Setor Marista', 'Apartamento com 3 suítes, 6 banheiros, 3 vagas de garagem e closet master no Sinfonia Eco Design, com varandas curvas modernas e áreas comuns completas. Localização estratégica próxima ao Parque Areião e gastronomia renomada, com lazer completo incluindo piscinas, sauna a vapor, academia e espaço gourmet.', 2800000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento Mobiliado no Setor Bueno, com 3 Suítes', 'Apartamento mobiliado de 153 m² no Setor Bueno, com 3 suítes com armários embutidos, cozinha americana com móveis planejados, decoração sofisticada, varanda com área de lazer no Persona Bueno com piscina, academia e salão de festas, próximo a shoppings, escolas e supermercados.', 1680000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento com 4 Suítes no Jardim Goiás', 'Cobertura duplex de 200 m² no Edifício Visage Arena, Jardim Goiás, com 4 suítes (duas americanas), suíte master com closet e varanda, área de lazer com piscina aquecida, churrasqueira, sala de estar, jantar, cozinha e área de serviço, 2 vagas de garagem e escaninho. Próximo ao Supermercado Moreira e Shopping Flamboyant.', 1700000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento no Lumina, com 4 Suítes à Venda no Marista', 'Apartamento de 221 m² no Setor Marista com 4 suítes, 4 vagas de garagem, closet, escritório, cozinha gourmet e móveis planejados de alto padrão. Localização próxima ao Parque Areião, com condomínio completo incluindo portaria 24h, academia, piscina, quadra esportiva e salão de festas.', 2300000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Duplex Mobiliado de 186 m² na Orla do Parque Flamboyant', 'Duplex mobiliado de 186 m² projetado pela Woo Arquitetura, com varanda envidraçada, vista para a cidade, automação completa, móveis assinados por Sergio Rodrigues e Jader Almeida, armários Oggi, projeto luminotécnico de destaque. Condomínio The One com quadra de tênis e piscina de borda infinita.', 2410000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento de 256 m² no Setor Marista, Vista para o Parque Areião, Quintas de Goyaz, 4 Suítes', 'Apartamento no Edifício Quintas do Goyaz com vista para o Parque Areião, 4 suítes, armários Terra, projeto de iluminação e ar-condicionado VRF, condomínio com área de lazer completa incluindo piscinas aquecidas, rooftop com piscina e área gourmet, brinquedoteca e salão de jogos.', 2450000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa de alto padrão Alphaville', 'Casa de alto padrão à venda no Alphaville com 4 suítes, sendo uma master com closet e hidromassagem. Escritório que pode se tornar a quinta suíte térrea, cinema e lazer completíssimo com piscina aquecida, sauna molhada e spa para 4 pessoas. Mix de mármores importados, projeto de iluminação arrojado, ambientes espaçosos e muita praticidade para o dia a dia.', 4900000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado Alphaville Araguaia, Goiânia - GO', 'Sobrado espetacular no Alphaville Flamboyant Residencial Araguaia, com terreno de 1.008 m² e 650 m² construídos. Conta com 4 suítes, destaque para suíte master de 80 m², garagem para 6 carros, piscina suspensa com vista infinita, cozinha gourmet equipada, adega para 400 garrafas, sistema de aquecimento solar, piscina aquecida, ar condicionado em todos os ambientes, persiana automatizada e irrigação automatizada no jardim com vista panorâmica para clube e Alphavilles.', 8390000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa térrea Jardins Itália, Goiânia', 'Casa térrea de 440 m² no Jardins Itália, com 4 suítes amplas, pé direito elevado e acabamento de altíssimo padrão. Infraestrutura com 3 vagas, cozinha integrada, espaço gourmet com churrasqueira, piscina, sauna, automação residencial, fechadura eletrônica, projeto luminotécnico, espera para split e poço artesiano. Localizada em condomínio exclusivo, oferece segurança e tranquilidade para sua família.', 5790000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado mobiliado 4 suítes no Jardins Madri, Goiânia', 'Sobrado mobiliado com 464 m² construídos em terreno de 615 m², com 4 suítes, sendo suíte master com closet amplo e academia privativa. Área social integrada com home cinema, cozinha gourmet, piscina com deck de madeira, banheira de hidromassagem e automação via Alexa. Possui elevador, adega, sala de jogos e acabamento impecável com móveis planejados. Sistema de aquecimento solar para eficiência energética.', 5600000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa mobiliada e decorada no Residencial Alphaville Flamboyant, Goiás', 'Casa mobiliada e decorada com 670 m² de área total em terreno de 926 m². Conta com 4 suítes, 7 banheiros, 4 vagas de garagem, medidas amplas do terreno e imóvel, excelente distribuição dos espaços e acabamento sofisticado.', 13000000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa térrea no Alphaville Flamboyant, Goiânia - GO', 'Casa térrea com 530 m² construídos em terreno de 882 m², com 4 suítes, sala com pé direito duplo, varanda com churrasqueira, piscina aquecida com deck molhado e hidromassagem, home theater, aquecimento solar para piscina, banheiros e cozinha, usina fotovoltaica, persianas automatizadas, previsão para elevador, paisagismo completo e 4 vagas cobertas de garagem.', 7200000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado mobiliado aldeia do Vale, Goiânia - GO', 'Sobrado mobiliado com 2.000 m² de terreno e 714 m² de construção, com 7 suítes, 8 banheiros, 15 vagas de garagem, elevador para 4 pessoas, automação avançada com cortinas automatizadas, adega ampla, academia, sauna, piscina aquecida, área verde, poço artesiano e placas fotovoltaicas.', 14000000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa mobiliada e decorada no Jardins Itália, Goiânia', 'Casa com 4 suítes amplas e iluminadas, 4 vagas de garagem, acabamentos exclusivos, fechadura digital, closet na suíte master, home office, sistema de energia solar, ar condicionado em todos os ambientes, cozinha integrada ao espaço gourmet com churrasqueira e piscina. Localizada em condomínio de alto padrão com segurança e comodidades.', 4850000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa térrea com 4 suítes no Portal do Sol Green', 'Casa térrea com 212,77 m² em terreno de 406 m², com 4 suítes plenas, 2 salas, 4 banheiros e 4 vagas de garagem. Destaque para sala com pé direito duplo de 6 metros, cozinha integrada à varanda gourmet, área de lazer completa com piscina aquecida com hidro, cascata, iluminação LED, churrasqueira, ducha fria e acabamentos de alta qualidade. Condomínio com lazer completo e localização privilegiada.', 2300000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado no Portal do Sol Garden, Goiânia', 'Sobrado exclusivo com 382 m² construídos em terreno de esquina de 575 m². Garagem para 3 carros, sala integrada com cozinha e jantar, lavabo, home office/suíte, varanda gourmet com piscina, suíte master e 3 suítes amplas. Sistema de irrigação e poço, elevador panorâmico, persianas integradas, geração de energia fotovoltaica híbrida de 12k, automação completa para iluminação e câmeras, acabamentos Eliane e pré-instalação para ar condicionado.', 4500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa térrea 4 suítes com piscina aquecida no Jardins Lisboa, Goiânia', 'Casa térrea com 200 m² construída em terreno de 377 m², com 4 suítes, sala com pé direito duplo de 6 metros, cozinha e varanda gourmet integradas. Área de lazer com piscina aquecida, cascata e churrasqueira. Condomínio Jardins Lisboa com academia, piscinas climatizadas, brinquedoteca, quadras esportivas e segurança 24 horas.', 2300000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Sobrado com 4 suítes no Jardins França, Goiânia', 'Sobrado com 418 m² de área total e 308 m² privativos, com 4 suítes espaçosas. Acabamentos de alto padrão, fechadura digital, aquecimento solar, energia solar, banheira de hidromassagem, espaço gourmet, piscina, jardim com árvores frutíferas e vista panorâmica. Excelente espaço para convivência e lazer em condomínio de alto padrão.', 3800000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa com bela piscina no Portal do Sol I, Goiânia', 'Casa com 368 m² de área privativa em terreno de 404 m², com 4 suítes, incluindo suíte master com banheira de hidromassagem. Piscina ampla com deck de madeira, espaço gourmet com churrasqueira a carvão, 4 vagas de garagem e segurança 24 horas no condomínio. Ambientes claros e arejados, design elegante e localização estratégica.', 2650000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa térrea no Residencial Goiânia Golfe Clube com 3 suítes', 'Casa de condomínio com 274 m² construídos em terreno de 566 m², com 3 suítes, 5 banheiros, cozinha americana integrada, área de serviço, despensa, lavabo, escritório e banheiro auxiliar. Área externa com espaço gourmet, piscina com hidro e deck. Energia solar e poço artesiano. Condomínio com segurança 24 horas e ótima localização.', 3500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Casa com 4 suítes, piscina aquecida e lazer completo no Goiânia Golfe Clube', 'Casa com 4 suítes e 6 banheiros, área social ampla e integrada, cozinha moderna, piscina aquecida com hidromassagem e cascata, venezianas automatizadas em alumínio preto, 3 vagas cobertas de garagem. Condomínio com academia, piscina, quadras esportivas, áreas verdes e segurança 24 horas, localizada em região tranquila e de fácil acesso.', 2650000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Lote Plateau D or Privilege com 1048 m² e fundo para mata', 'Terreno residencial exclusivo com 1.048 m² no Plateau D or, localizado em ponto estratégico do condomínio e com fundo voltado para mata. Oferece infraestrutura completa com academia, áreas de lazer, espaços verdes e mirantes. Próximo à entrada e academia, garantindo comodidade e qualidade de vida em ambiente seguro e harmonioso.', 3140000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura de alto padrão com 5 suítes no Setor Marista, Goiânia', 'Cobertura sofisticada com 414 m² e 5 suítes, sendo uma master com closet, piscina aquecida com cascata, sauna, espaço gourmet montado e semi mobiliada. Conta com 3 vagas de garagem e condomínio com infraestrutura premium. Vista panorâmica impressionante para o lago.', 4190000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura na Orla do Parque Vaca Brava com 590 m² e 4 suítes', 'Luxuosa cobertura no Edifício Zeus Park House, Setor Bueno, com 590 m², 4 suítes, 7 banheiros e 5 vagas. Destaques para iluminação natural, vista relaxante, espaços ao ar livre e ambientes terapêuticos. Projeto que prioriza saúde, equilíbrio e conforto em todas as áreas do apartamento.', 6980000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura mobiliada no Setor Bueno com 220 m² e 3 suítes', 'Cobertura 100% mobiliada com 220 m², 3 suítes, 5 banheiros e 4 vagas de garagem. Ambientes repletos de armários e decoração prática para morar com conforto. Localização privilegiada no Setor Bueno.', 2200000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Penthouse com 612 m², 5 suítes, 6 vagas e vista panorâmica no Setor Marista', 'Penthouse inédita e nunca habitada no 37º andar do Edifício Sinfonia Ecodesign. Área privativa de 612 m² com 5 suítes amplas, ofurô privativo, área gourmet interna e espetacular vista da cidade. Possui 6 vagas de garagem e localização privilegiada perto do Parque Areião e Alameda Ricardo Paranhos.', 7956000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Penthouse Poème Lago das Rosas com 372 m², 3 suítes e 4 vagas no Setor Oeste', 'Penthouse com 372 m², 3 suítes, 7 banheiros e 4 vagas, localizada na Alameda das Rosas. Residência sofisticada com piso de madeira, varanda com churrasqueira, piscina e suíte master com dois banheiros. Condomínio de alto padrão com academia, piscinas e segurança 24 horas.', 3500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Cobertura duplex no Setor Marista, Ed. Gran Finestra', 'Cobertura duplex em localização nobre próxima ao Shopping Bougainville. Com amplas áreas de lazer, piscina, churrasqueira, pé-direito duplo, suíte master com dois closets, elevador privativo para ambos os pavimentos, 4 vagas de garagem e escaninho. Condomínio seguro e bem localizado.', 4600000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Belíssima cobertura em Barueri, SP, com 530 m² e 4 suítes', 'Cobertura de alto padrão em Barueri com 530 m², 4 suítes sendo uma master, ampla sala, cozinha, terraço com piscina e vista panorâmica. Condomínio com piscinas coberta e externa, sauna, quadra de futebol com gramado sintético, salão de festas, academia e ótima localização próximo ao Colégio Mackenzie e shopping Iguatemi.', 5500000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Charmoso flat mobiliado de 31 m² no Setor Marista, Goiânia', 'Flat mobiliado no QS Marista, com 31 m², suíte, banheiro e vaga de garagem. Condomínio com portaria 24h, academia, piscina exclusiva Red Pool e salão de festas. Localização privilegiada no bairro Marista, próximo a restaurantes, centros comerciais e opções de lazer.', 390000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Flat mobiliado à venda no QS Marista com 31 m²', 'Flat mobiliado de 31 m² com suíte, banheiro e vaga de garagem no QS Marista. O condomínio oferece infraestrutura completa, inclusive portaria 24h, academia, piscina, salão de festas e acessibilidade para PCD. Excelente oportunidade para morar ou investir em localização nobre de Goiânia.', 390000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Flat com 49 m² no Liv Urban Marista, Goiânia', 'Flat com 49 m² e 38 m² de área privativa, 1 quarto com suíte, banheiro e vaga de garagem. Condomínio completo com academia, coworking, espaço pet, piscinas, sauna, salão de festas, brinquedoteca e muito mais. Pet friendly, varanda integrada com vidro e localização estratégica próxima ao Parque Areião.', 490000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Flat mobiliado no Trend Home com 39 m² no Jardim Goiás', 'Flat mobiliado com 39 m², 1 quarto, 1 suíte, 1 banheiro e 1 vaga no Jardim Goiás. Ambiente acolhedor com cozinha integrada, pronto para morar. Localização privilegiada próxima a parques, restaurantes, escolas e comércio. Ideal para conforto e praticidade no dia a dia.', 450000.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Lote Plateau D or UNIQUE com 654 m² na 2ª etapa', 'Terreno quitado de 654 m² na 2ª etapa do Plateau D or, situado na quadra 58. Excelente oportunidade para investimento em área valorizada.', 1896600.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Apartamento exclusivo com 4 suítes e pé direito elevado em Goiânia', 'Apartamento na planta com 262,87 m², 4 suítes, 5 banheiros, 3 vagas de garagem, cozinha americana, área de serviço, sala de jantar, lavabo, espaço gourmet e churrasqueira. Destaque para pé direito elevado, ambientes amplos e acabamento de alto padrão em condomínio com infraestrutura completa e segurança.', 3613221.00, imoveis_category_id, residencial_subcat_id, true, false, 1),
    ('Loft Mobiliado e Decorado com 41 m², 1 Suíte e 1 Vaga à Venda no Setor Bueno', 'Descubra o conforto e modernidade neste loft de 41 m², localizado no Edifício Citizen Home, Setor Bueno, Goiânia. Com uma suíte elegante e espaços integrados entre sala e cozinha, este loft oferece praticidade e estilo de vida contemporâneo. Móveis e decoração cuidadosamente selecionados garantem um ambiente pronto para morar. Desfrute das comodidades do Citizen Home, que incluem academia, área de lazer, churrasqueira gourmet, piscina e muito mais. Tecnologia e segurança são prioridades, com fechaduras eletrônicas para praticidade e tranquilidade no dia a dia. Situado no Setor Bueno, o loft proporciona fácil acesso a shopping centers, transporte público e vias importantes da cidade. Não perca a oportunidade de viver com estilo e comodidade. Agende sua visita e conheça seu novo lar no Citizen Home.', 550000.00, imoveis_category_id, residencial_subcat_id, true, false, 1);
    
    -- Insert commercial properties
    INSERT INTO products (name, description, price, category_id, subcategory_id, published, featured, stock_quantity) VALUES
    ('Laje Inteira em Prédio Comercial Moderno no Setor Oeste, Goiânia', 'Laje inteira em prédio comercial moderno com 1.210m², piso carpete e porcelanato acetinado, várias salas e espaços com divisórias modernas. Inclui 29 vagas de garagem exclusivas e vista panorâmica da cidade. Próximo a concessionárias e supermercados. Ideal para grandes empresas e bancos.', 9500000.00, imoveis_category_id, comercial_subcat_id, true, false, 1),
    ('Prédio comercial novo no Setor Oeste, Goiânia', 'Prédio comercial novo e desocupado com 4.901 m² de área total e privativa, 11 salas, 11 banheiros e 50 vagas de estacionamento. Com nove lajes de 270 m² de vão livre, incluindo lajes com pé direito duplo, localizado próximo a bancos, hospitais e hotéis, ideal para diversos empreendimentos comerciais.', 40000000.00, imoveis_category_id, comercial_subcat_id, true, false, 1);
    
    -- Insert rural properties
    INSERT INTO products (name, description, price, category_id, subcategory_id, published, featured, stock_quantity) VALUES
    ('Sítio Luxuoso com Estrutura Completa em 7 Alqueires em Aragoiânia', 'Propriedade rural com 4 suítes principais, 3 chalés, capacidade para 100 veículos, lago com deck e rampa de jet-ski, pomar com variedades frutíferas, piscina com hidromassagem, campo de futebol society e salão de festas para 300 pessoas. Infraestrutura completa com irrigação automatizada, poço artesiano, monitoramento por câmeras e casa principal equipada com conforto e móveis planejados.', 7500000.00, imoveis_category_id, rural_subcat_id, true, false, 1),
    ('Chácara de Lazer em Caldas Novas com 18 Hectares e 634 m² Construídos', 'Propriedade rural na Fazenda Cocal próxima a Caldas Novas, com 4 quartos (3 suítes), casa de hóspedes, casa do caseiro, viveiro para aves de 600 m², pomares e 3 lagos para pesca esportiva. Estrutura completa com animais exóticos, ambientes amplos e a 10 minutos do centro da cidade. Ideal para lazer, moradia ou investimento.', 6800000.00, imoveis_category_id, rural_subcat_id, true, false, 1),
    ('Chácara no Condomínio Recanto das Garças à beira do Lago Corumbá IV', 'Espaçosa propriedade no Recanto das Garças com mais de 6.000 m², incluindo casa principal com 4 suítes, casas auxiliares, piscina aquecida com tratamento de ozônio, salão de jogos com vista panorâmica, pergolado, bangalô, tanque de peixes e pomar. Infraestrutura completa com quadra de areia, lareira charmosa e mina d água que alimenta lagos. Fácil acesso a Goiânia (50 km) e Brasília (70 km).', 3200000.00, imoveis_category_id, rural_subcat_id, true, false, 1),
    ('Chácara mobiliada e decorada em condomínio Águas da Serra, Hidrolândia', 'Rancho exclusivo mobiliado em terreno de 2.000 m² com 420 m² construídos, 4 suítes, escritório, cozinha integrada, piscina de borda infinita e poço artesiano. Condomínio com área verde, lagos, quadras esportivas, churrasqueiras, salão de festas, restaurante e fazendinha com animais. Localização a 30 minutos de Goiânia pela BR-153.', 4980000.00, imoveis_category_id, rural_subcat_id, true, false, 1);

END $$;
