
-- Add decoration products to the existing Decoração category and subcategories
DO $$
DECLARE
    decoracao_category_id uuid;
    esculturas_subcat_id uuid;
    miniaturas_subcat_id uuid;
    obras_arte_subcat_id uuid;
BEGIN
    -- Get the existing "Decoração" category ID
    SELECT id INTO decoracao_category_id FROM categories WHERE name = 'Decoração';
    
    -- Get existing subcategory IDs
    SELECT id INTO esculturas_subcat_id FROM subcategories WHERE name = 'Esculturas' AND category_id = decoracao_category_id;
    SELECT id INTO miniaturas_subcat_id FROM subcategories WHERE name = 'Miniaturas' AND category_id = decoracao_category_id;
    SELECT id INTO obras_arte_subcat_id FROM subcategories WHERE name = 'Obras de Arte' AND category_id = decoracao_category_id;
    
    -- Insert products into Esculturas subcategory
    INSERT INTO products (name, description, price, category_id, subcategory_id, published, featured, stock_quantity) VALUES
    ('ESCULTURA F1 LEWIS HAMILTON', 'Escultura em fibra de vidro de alta qualidade, com pneus de borracha e acabamento 3D. Pintura e verniz automotiva. Dimensões: 2,40m x 1,00m.', 18900.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('ESCULTURA F1 AYRTON SENNA LOTUS 99T', 'Escultura em fibra de vidro de alta qualidade com pneus de borracha e acabamento 3D. Pintura e verniz automotiva. Dimensões: 2,20m x 1,00m.', 18900.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('ESCULTURA F1 RED BULL MAX VERSTAPPEN', 'Escultura em fibra de vidro de alta qualidade, pneus de borracha e acabamento 3D, com pintura e verniz automotiva. Dimensões: 2,40m x 1,00m.', 18900.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('FOREST KING', 'Escultura autoral de gorila em aço carbono resistente e sustentável, revestida com chapas de aço para alta durabilidade. Estilo figurativo geométrico. Dimensões: altura 1,00m, largura 62cm, comprimento 1,00m.', 22000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('LITTLE MONKEY GRAIN', 'Escultura de macaco-aranha feita em chapa de aço carbono 1,5mm, com acabamento primer e pintura automotiva semi brilho. Vários tamanhos e cores disponíveis sob encomenda. Dimensões: altura 1,00m, largura 56cm, comprimento 1,00m.', 20000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('BLACK PANTHER', 'Escultura metálica resistente da pantera negra em posição de ataque, feita em chapa de aço carbono 1,5mm, acabamento primer e pintura automotiva semi brilho. Disponível sob encomenda. Dimensões: altura 46cm, largura 39,8cm, comprimento 1,50m.', 22000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('BAD LION ll', 'Escultura autoral de leão sentado em chapa de aço carbono 1,5mm, com acabamento primer e pintura automotiva semi brilho. Peça resistente, disponível em vários tamanhos e cores. Dimensões: altura 1,00m, largura 56,5cm, comprimento 91cm.', 22000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('FINANCIAL BEAR', 'Escultura representando o urso financeiro, feito em chapa de aço carbono 1,5mm com acabamento primer e pintura automotiva semi brilho. Design moderno, ideal para ambientes corporativos. Dimensões: altura 1,50m, largura 79,5cm, comprimento 1,00m.', 24000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('FINANCIAL BULL', 'Escultura metálica do touro financeiro em chapa de aço carbono 1,5mm, acabamento primer e pintura automotiva semi brilho. Design arrojado com patas no chão e chifres erguidos. Dimensões: altura 1,00m, largura 64cm, comprimento 1,67m.', 24000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('JUNGLE RINO', 'Escultura moderna de rinoceronte feita em chapa de aço carbono 1,5mm, acabamento primer e pintura automotiva semi brilho. Peça autoral e resistente, disponível em vários tamanhos e cores. Dimensões: altura 70cm, largura 50cm, comprimento 1,30m.', 22000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('THE LEGEND - TWO COLORS', 'Escultura autoral de alce gigante (Megaloceros giganteus) em chapa de aço carbono 2mm, com acabamento primer e pintura automotiva semi brilho. Disponível sob encomenda. Dimensões: altura 1,50m, largura 1,30m, comprimento 1,17m.', 26000.00, decoracao_category_id, esculturas_subcat_id, true, false, 1),
    ('Miniatura Motor 250S Opala Escala 1:3 Com Base e Número de Série Único', 'Miniatura detalhada do motor 250S usado no Chevrolet Opala 6 cilindros (1968-1988). Peso 0,5 kg, dimensões base 30x20cm, motor 28x18x21cm. Produto personalizado com número de série único.', 1299.00, decoracao_category_id, esculturas_subcat_id, true, false, 1);
    
    -- Insert products into Miniaturas subcategory
    INSERT INTO products (name, description, price, category_id, subcategory_id, published, featured, stock_quantity) VALUES
    ('Miniatura Motor Ford Mustang GT Performance Escala 1:5 Com Expositor Acrílico', 'Miniatura do motor Ford Mustang GT Performance com peso de 2 kg e dimensões 30x20x20 cm. Produto feito sob encomenda com prazo de 15 dias.', 1799.00, decoracao_category_id, miniaturas_subcat_id, true, false, 1),
    ('Motor M64 Porsche 993 Escala 1:3', 'Réplica em miniatura do motor Porsche 993 (1994-1998) em escala 1:3, peso 2 kg, dimensões 30x20x20 cm. Produto feito sob encomenda com prazo de 15 dias.', 2499.00, decoracao_category_id, miniaturas_subcat_id, true, false, 1),
    ('Miniatura Motor Maverick V8 1:5 Com Expositor Acrílico', 'Miniatura detalhada do motor V8 do Maverick, pesando 1 kg, dimensões 30x20x20 cm. Ideal para colecionadores e fãs de carros clássicos.', 1799.00, decoracao_category_id, miniaturas_subcat_id, true, false, 1),
    ('Miniatura Motor McLaren F1 Escala 1:5 Com Expositor em Acrílico', 'Miniatura do motor McLaren F1 S702 V12 escala 1:5, peso 1 kg, dimensões 10x10x10 cm. Peça meticulosamente reproduzida, acompanha suporte em acrílico.', 1949.00, decoracao_category_id, miniaturas_subcat_id, true, false, 1),
    ('Motor 2JZ Toyota Supra Escala 1:5', 'Réplica detalhada do motor 2JZ Single Turbo do Toyota Supra, peso 2,5 kg, dimensões 32x22x22 cm. Produto sob encomenda com acabamento de alta qualidade.', 1799.00, decoracao_category_id, miniaturas_subcat_id, true, false, 1);
    
    -- Insert products into Obras de Arte subcategory
    INSERT INTO products (name, description, price, category_id, subcategory_id, published, featured, stock_quantity) VALUES
    ('A RESPOSTA QUE VEM DE DEUS', 'Tela com técnica acrílico e spray, dimensões 1,20x1,20 m. Obra representando resiliência, fé e bênçãos divinas com cores vibrantes e simbolismos espirituais.', 12000.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('A TECNOLOGIA ARTÍSTICA', 'Obra em acrílico misto, bastão de giz pastel e caneta sobre papel, dimensões 0,30x0,15 cm. Expressa avanço tecnológico e criatividade com cores vibrantes. Série LG x Samuel Caixeta.', 3400.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('QUAL O VALOR DA SUA FAMÍLIA', 'Tela em misto sobre papel, dimensões 0,45x0,45 cm, inspirada na valorização da família e experiências na Grécia. Inclui jornal colado e simbolismos pessoais.', 3950.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('CULTIVANDO O FUTURO', 'Tela em acrílico sobre tela, dimensões 1,00x1,30 m. Representa persistência e cuidado interior com simbolismos de flores e borboletas. Ano 2025.', 14900.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('RESSIGNIFICANDO VALORES', 'Obra em misto sobre acrílico, dimensões 0,40x0,50 m. Retrata valorização da pessoa e ressignificação do que é ignorado. Ano 2025.', 3700.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('A MELODIA DE DENTRO DA MINHA MENTE', 'Acrílico misto sobre tela, dimensões 1,40 x 1,10 m. Expressa a conexão profunda do artista com a música, que embala sua criatividade como uma sinfonia divina. A obra é uma visão mental enquanto pinta, inspirada por uma música que representa a essência da arte e a ligação intimista com Deus, fonte máxima de toda expressão artística. Também reflete a criatividade explorada em seu livro sobre a profissão artística.', 10200.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('VOCÊ É A PRÓPRIA NATUREZA', 'Acrílico misto e bastão sobre tela, dimensões 1,50 x 1,20 m. A obra traz uma reflexão sobre o respeito à natureza, nossa verdadeira mãe, alertando para as consequências da destruição ambiental. Apela à consciência, compaixão e responsabilidade para preservar a Terra, ressaltando a urgência de reciclar, reutilizar e respeitar o planeta, que é nossa única casa.', 11200.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('VISÃO DO FUTURO', 'Técnica mista sobre papiro, dimensões 0,40 x 0,50 m. Obra criada para exposição no Egito, onde o artista foi o único brasileiro, diante de 180 artistas internacionais. Representa um diálogo entre gerações ao mostrar, sobre o papiro – o primeiro "papel" –, uma visão futurista com tecnologia e inteligência artificial, simbolizados por um personagem narrigudo e um olho que representa o olhar para além do tempo. Inclui também representações em arte digital e NFT.', 4300.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('ENTRE RASGOS E CORES, A HERANÇA FAMILIAR', 'Acrílico misto sobre tela e jornal da Grécia, dimensões 1,20 x 1,00 m. Fundo bege simboliza a passagem do tempo e a herança familiar. Detalhes em preto com revistas e tecidos rasgados evocam as gerações passadas, homenageando avós e tataravós. Rasgos contam histórias e memórias que moldam a identidade do artista, enquanto o neon verde representa a conexão entre passado e avanço tecnológico.', 12300.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('LEGADO DE PRINCÍPIOS FAMILIARES', 'Acrílico misto sobre tela e bastão, dimensões 1,80 x 1,20 m. Com símbolos em azul, laranja e preto, a obra expressa princípios familiares: paz de Deus, alegria da fé e reflexão espiritual. Retrata a busca pelo equilíbrio entre tradição e valores atuais, celebrando a unidade do corpo, alma e espírito e o viver de uma fé harmoniosa no século XXI.', 17100.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('COMO VOCÊ TEM CONTROLADO SUA MISSÃO?', 'Acrílico misto sobre tela, dimensões 1,60 x 0,90 m. Inspirada em Moisés 3:17, representa a liberdade dada por Deus para escolher o caminho do bem ou do mal. Simboliza a vida como um jogo onde cada um dirige seu veículo - missão e propósito - colhendo os frutos das próprias escolhas, enfatizando a responsabilidade individual diante da liberdade espiritual.', 9700.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('OS TRAÇOS QUE NOS MOLDAM', 'Acrílico sobre tela, dimensões 0,40 x 0,50 m. Retrata a formação única de cada ser humano, à imagem do Oleiro Divino, responsável por criar nossos traços, qualidades e dificuldades. Explora a ideia de que o que parece torto aos olhos humanos é o diferencial dado por Deus, e incentiva a viver o propósito individual além das imperfeições.', 6400.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('SEU CORAÇÃO É O ÁRBITRO DAS SUAS DECISÕES', 'Acrílico e spray sobre tela, dimensões 0,70 x 0,70 m. Reflete sobre as dores diárias, traições e amarguras que ferem o coração e impedem o amor. Baseada em Hebreus 12:15, alerta para o risco da raiz de amargura que contamina a vida, enfatizando a necessidade de superar emoções negativas para manter o amor vivo e o sentido da vida.', 4780.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('VOLTANDO AO CONTATO PESSOAL', 'Acrílico sobre tela, dimensões 1,50 x 1,50 m, ano 2020. Retrata Armonildo, um garçom representando quem serve ao próximo, em preto e branco, mas com interior colorido simbolizando vida e autenticidade. O personagem carrega um celular antigo – primeiro comercializado no Brasil – que simboliza a conexão genuína perdida na era digital, convocando para resgatar encontros humanos e a intimidade verdadeira.', 17000.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('A MELHOR FORMA DE VENCER O INIMIGO', 'Acrílico e spray sobre tela, dimensões 1,60 x 1,00 m. Inspirada em Mateus 5, esta obra celebra o dom divino de amar o inimigo como luz na escuridão, multiplicando o amor na alma e promovendo paz interior por meio do perdão e oração pelos perseguidores.', 14300.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('O PODER DA DOMINÂNCIA', 'Pintura acrílica sobre tela, dimensões 1,50 x 1,00 m, data 15/01/2019. Retrata a influência negativa de uma família sobre o filho no centro da obra, com seus sonhos sufocados pelos objetivos alheios impostos. Faz crítica à imposição de trajetórias profissionais que não respeitam os desejos individuais dos jovens.', 7000.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('MENTE BLINDADA', 'Acrílico e spray sobre tela, dimensões 1,80 x 1,20 m. Reflete o impacto dos valores e crenças formados desde a infância na definição do que fazemos e como agimos. Inspirada em Provérbios 22:6, destaca a importância da coerência entre atitudes e valores, convidando à reflexão sobre as convicções pessoais.', 16300.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('LIBERTANDO AS AMARRAS', 'Pintura acrílica sobre tela, dimensões 1,50 x 1,50 m, ano 2018. Representa a libertação dos grilhões da vida comum e o poder transformador de pessoas que nos compreendem e nos desafiam a uma jornada extraordinária. As cores vivas e traços fortes simbolizam a coragem para romper limites, e o azeite derramado evoca a unção e o milagre do despertar para o propósito divino e significativo.', 16500.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('UMA ALMA RICA', 'Tela em acrílico, dimensões 1,20 x 0,80 m. Expressa a visão de prosperidade baseada na riqueza da alma, que se manifesta por decisões sábias e pelo uso dos dons dados por Deus, valorizando momentos e uma vida com propósito, sem foco em bens materiais.', 8000.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('DEPENDA DE DEUS', 'Acrílico e spray sobre tela, dimensões 2,00 x 2,90 m. Transmite a certeza de que Deus mantém o controle das situações, esculpindo nossa alma com paciência e fé. A obra destaca a organização divina da vida, o ensinamento da verdadeira lógica e o convite para confiar sem dúvidas no cuidado divino.', 34850.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('O MOSAICO DAS PERSPECTIVAS', 'Acrílico sobre tela, dimensões 1,20 x 0,80 m, data 2018. Celebra a diversidade dos olhares e percepções individuais, mostrando como cada visão é única e enriquecedora. As cores azuis vivas, vermelho e amarelo simbolizam a pluralidade e liberdade de expressão, valorizando a empatia e o respeito pelas distintas perspectivas humanas.', 5800.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1),
    ('A IDADE, APENAS EM NÚMEROS', 'Tela em acrílico, dimensões 2,70 x 2,00 m. Retrata o artista com sua bisavó, simbolizando perseverança e a importância de nunca desistir dos sonhos independentemente da idade ou circunstâncias. Encoraja a superar julgamentos e dar o primeiro passo rumo às metas.', 15000.00, decoracao_category_id, obras_arte_subcat_id, true, false, 1);

END $$;
