
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlocqbwyhhympjwpyzjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsb2NxYnd5aGh5bXBqd3B5empjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxMzk3MTIsImV4cCI6MjA5MTcxNTcxMn0.WkO8fYlWnUTPt0NRE9ZiTShFZ_ZoyQ_7ybOIdpIwBQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
