
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gytzdhfbmmrsanrhquut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dHpkaGZibW1yc2FucmhxdXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTcwNzIsImV4cCI6MjA2MjMzMzA3Mn0.ZSUyLufyXKd8YzgyFFWhEV6FzI9cyGogxdPPVDovDYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
